[package]
name = "ygsuf/helloworld-3"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
signal = "sleitnick/signal@2.0.1"
roact = "roblox/roact@1.4.4"
janitor = "howmanysmall/janitor@1.16.0"
